### PR TITLE
Rewrite slab making it more idiomatic

### PR DESCRIPTION
**Pull request by carllerche**
he goal of the rewrite is to make the APIs more idiomatic and more in line with other types in the Rust std. Also, any existing function that wasn't necessary has been removed in favor of a smaller API surface.

### CODE REVIEW

**Comment by guanqun** [comment]
When will this get merged?

**Comment by carllerche** [comment]
Good question... I forgot about this :) I should catch back up.

**Comment by carllerche** [comment]
I forgot that I wrote this... but it looks good to me!

**Comment by peterdelevoryas** [comment]
Hello @carllerche, I was using `slab` prior to this change, and I found the index type parameter great, even though it might have only added a tiny amount of practical type safety to my use cases. I'm disappointed that it was removed, and while I don't expect you to revert the change, I would be curious if you had more justification for the change. Personally, I don't see how a generic index type that implements `From<usize>` and `Into<usize>` is less idiomatic than the `HashSet` and `HashMap` API's which require the key to implement `Hash`, but I would be very interested to know if there were some discussions elsewhere that I'm not aware of, or if you have further justification for it. Thanks!

**Comment by carllerche** [comment]
It was just more complexity that didn't seem to carry its weight. You can always decorate the slab to take your custom key type.

**Comment by peterdelevoryas** [comment]
I see, thanks for humoring me!

**Pull request merged**
