### PR TITLE
impl `FromIterator<(usize, T)>` for `Slab<T>`

### PR DESCRIPTION
**Pull request by flier**
for deserialize `Slab` with fixed key/value pair, resolve #41

### CODE REVIEW

**Comment by carllerche** [comment]
Sorry for the delay. I am OK with accepting a `FromIterator` implementation. However, as far as I can tell, this implementation is buggy if the iterator is not ordered. Would you be able to add some tests for loading a slab when the indices are decrementing and in random order?

**Comment by carllerche** [comment]
Thanks, is there a way to do this without the vec allocation / sort?

Perhaps it could be done in two iterations. The first creates the internal vec storage, iterates the provided iter, and inserts items into their slots. The second pass iterates the storage vec and creates the "free slot" linked list?

**Comment by flier** [comment]
I guess the cost is same to use a `Vec::sort`, because we have to iterates the whole iterator in the first pass to got a sorted internal vec storage. On the other hand, I can submit another PR to impl FromIterator<T> for Slab<T> which don't need the sorted effort.

**Comment by vadixidav** [comment]
I would really like this functionality so I can more easily serialize `Slab`. I think it is okay to accept a slow version that sorts and then create an issue to track the completion of a more efficient implementation that can be completed later.

**Comment by carllerche** [comment]
The changes provided by this PR are covered by #62.

Thanks for getting the ball rolling 👍

**Pull request closed without merging**
