### PR TITLE
Implement replace_with method

### PR DESCRIPTION
**Pull request by tailhook**
The method allows to consume item by value and (optionally) return a
value to put into the place. It also allows to return some useful value
to the caller.

Very useful for implementing connection state machines using mio.

### CODE REVIEW

**Comment by carllerche** [comment]
Sorry for the delay. I have a few thoughts / questions.

* Should the function take an `Option<T>` vs. `T` to handle the case of the slot being currently empty (vs. returning `Err`). I'm not sure this is better, so I am wondering what you think.

* Instead of having the function return a tuple (with an optional return value), why not only return the new type? Wanting to return an extra return value as well seems like the less common case and it should be possible to update a stack variable.

**Comment by tailhook** [comment]
> Should the function take an Option<T> vs. T to handle the case of the slot being currently empty (vs. returning Err). I'm not sure this is better, so I am wondering what you think.

I think it's easy to turn Result into Option. And warning of unused result may help. I.e. in my case of using the method for connection state machine with mio, I would have to just use unwrap(), because spurious event for empty slot is just an error. But it's the serious error. It means something wrong with my register/deregister calls. So I don't want it to pass unnoticed.

> Instead of having the function return a tuple (with an optional return value), why not only return the new type? Wanting to return an extra return value as well seems like the less common case and it should be possible to update a stack variable.

Well it's possible. That was probably a obsessive desire to have less mutability. In fact both using mutable variable in closure and returning two values are equally creepy. But after thinking a little more I'm inclined to say that returning value should be less common.

In case you ask: it's important to have new value as an Option. Deleting connection by connection state machine itself is very useful operation.

**Comment by carllerche** [comment]
I agree about returning `Option<T>` to delete the value (I may have omitted that in my original comment).

So, I guess we agree to simply return `Option<T>` vs. the tuple. If you can update the PR, I will merge it. Thanks.

**Comment by tailhook** [comment]
Ok. I've amended the commit.

**Comment by carllerche** [comment]
Thanks

**Pull request merged**
