### PR TITLE
 serialize Slab with `serde`

### PR DESCRIPTION
**Pull request by flier**

### CODE REVIEW

**Comment by carllerche** [comment]
Thanks for the PR. However, i think that id rather avoid the serde dependency. slab isn’t intended to be a collection, more just a chunk of memory. This would be like implementing Serde on a heap allocator. 

That said. You should be able to wrap slab and impl this if you really need it.

**Comment by flier** [comment]
agree, but it need Slab expose some internal API, for example, insert a key/value with `insert_at`

**Comment by carllerche** [comment]
`insert_at` is not safe to impl. It would break the internal data structure. It would be like serializing / deserializing pointer addresses. It doesn't make much sense IMO.

**Comment by flier** [comment]
ok, maybe we could add new `Slab::from_iter<T: IntoIterator<Item = (K, V)>>(iter: T) -> Self` for deserializing?

**Comment by carllerche** [comment]
Again, I would suggest that instead of serializing the `Slab` with the indices (which should be considered similar to pointers), you serialize the actual data that is pertinent in such a way that the memory storage is not included.

Doing so would allow more efficient deserialization too.

Imagine you use a slab a bunch and end up with a slab of capacity 1MM but only two entries (at 0 and at 999,999). When deserializing, even though there are only two values, you would need to:

1) Initialize a vector of 1MM capacity
2) Insert the two elements
3) Reconstruct the internal data structure of slab to make it consistent.

Maybe you should try opening an issue on `serde` to get more clarity in how to implement a serializer for your case.

I'm going to close the issue for now, but feel free to continue the discussion here.

**Comment by flier** [comment]
In fact, most of time, I use Slab key as a external ID (maybe message or packet ID), it means I need serialize the data with ID to storage, that's why I must deserialize data to Slab with same ID.

**Pull request closed without merging**
