### PR TITLE
 Back slab with a Vector

### PR DESCRIPTION
**Pull request by hjr3**
- uses a vector instead of a boxed slice
- remove Entry implementation. slab now uses the Entry enum directly.
- modify some functions for better code re-use
- add additional tests

Also, added retain method to slab.

### CODE REVIEW

**Comment by carllerche** [comment]
It seems that this won't work on Rust 1.0 anymore. I'm fine bumping it to 1.1? I don't know which version is needed though. Could you try bumping CI to 1.1?

**Comment by hjr3** [comment]
Per https://github.com/rust-lang/rust/issues/15609 this now requires 1.2. Is that too high?

**Comment by carllerche** [comment]
Probably fine. I will just have to update mio to depend on 1.2 as well

**Comment by hjr3** [comment]
Or I can re-implement `as_mut` on `Entry` and we keep 1.0 compatibility.

**Comment by carllerche** [comment]
sure

**Comment by hjr3** [comment]
@carllerche I retained rust 1.0 compat.

**Comment by arthurprs** [comment]
Paves way to solve #7 as well.

**Comment by carllerche** [comment]
Thanks!

**Pull request merged**
